export const amsDashboardData = {
  persona: {
    name: "Tony",
    title: "Head of AMS",
    role: "Head of AMS",
    domain: "AI for AMS",
    domainName: "Application Management Services",
    platform: "AMS-OPS",
    shift: "EMEA Day Ops | Active",
    shiftProgress: 68,
    statusText: "Enterprise Tier-1 Services Active Workspace - 4 Active Clusters - 12 Pending Problem Records",
    slaHealth: "99.1%",
    aiResolutionRate: "78.4%"
  },
  overviewStats: {
    p1Blocked: 2,
    p2InReview: 5,
    p3InProgress: 14,
    p4Backlog: 28,
    totalIncidentsToday: 49,
    autoResolvedToday: 38,
    mttd: {
      current: "4.2m",
      baseline: "26.0m",
      reduction: "83.8% faster",
      trend: "down"
    },
    mttr: {
      current: "18.5m",
      baseline: "112.0m",
      reduction: "83.5% faster",
      trend: "down"
    },
    slaCompliance: "99.2%",
    stabilityScore: "99.85%",
    problemToChangeRate: "64.3%",
    costSavedYtd: "$412,500",
    engineeringHoursSaved: "1,240 hrs"
  },
  incidentSeverityBreakdown: [
    { severity: "P1 - Critical", count: 2, slaTarget: "15m", breached: 0, status: "Investigating" },
    { severity: "P2 - Major", count: 5, slaTarget: "45m", breached: 0, status: "Under Mitigation" },
    { severity: "P3 - Moderate", count: 14, slaTarget: "4h", breached: 1, status: "Assigned" },
    { severity: "P4 - Minor", count: 28, slaTarget: "24h", breached: 0, status: "Auto-Queued" }
  ],
  recurringClusters: [
    {
      id: "CLUSTER-881",
      title: "Kafka Consumer Lag & Rebalance Cascades",
      affectedService: "Order-to-Cash Telematics Broker",
      portfolio: "Connected Vehicle Core",
      frequency: "14 occurrences in 7 days",
      impactLevel: "Critical",
      rootCauseSummary: "Partition uneven distribution under peak EU vehicle heartbeat bursts",
      aiRecommendation: "Dynamic partition rebalance agent triggered + Auto-scale consumer group pods to 12",
      status: "Mitigation in Progress",
      riskScore: 92,
      problemTicketCreated: "PRB-4092",
      changeRequestLinked: "CR-8921"
    },
    {
      id: "CLUSTER-882",
      title: "SAP S/4HANA OData Gateway Connection Pool Exhaustion",
      affectedService: "Dealer Invoicing & Part Catalog API",
      portfolio: "Global Commercial Operations",
      frequency: "8 occurrences in 48 hours",
      impactLevel: "High",
      rootCauseSummary: "Unclosed HTTP client sessions during dealer batch inventory sync",
      aiRecommendation: "Apply circuit breaker policy in Envoy mesh & initiate PR to patch connection pool leak",
      status: "Review Required",
      riskScore: 78,
      problemTicketCreated: "PRB-4088",
      changeRequestLinked: "CR-8914"
    },
    {
      id: "CLUSTER-883",
      title: "Vehicle Telematics GPS Ingestion Packet Drops",
      affectedService: "Fleet Edge Telemetry Pipeline",
      portfolio: "Stellantis Cloud Platform",
      frequency: "19 occurrences in 5 days",
      impactLevel: "Elevated",
      rootCauseSummary: "UDP buffer saturation during regional 4G reconnect surges",
      aiRecommendation: "Agentic load shedder active; 94% telemetry buffered without loss",
      status: "Stable with Workaround",
      riskScore: 65,
      problemTicketCreated: "PRB-4074",
      changeRequestLinked: "CR-8902"
    },
    {
      id: "CLUSTER-884",
      title: "OAuth2 Token Validation Redis Cluster Cache Thrashing",
      affectedService: "Customer Mobile Identity Gateway",
      portfolio: "Digital Customer Experience",
      frequency: "6 occurrences in 24 hours",
      impactLevel: "Moderate",
      rootCauseSummary: "TTL synchronization collision on JWT revocation list invalidation",
      aiRecommendation: "Apply jitter to TTL caching and convert to distributed Redis read-replicas",
      status: "Proposed Change",
      riskScore: 54,
      problemTicketCreated: "PRB-4069",
      changeRequestLinked: "CR-8898"
    }
  ],
  problemToChangePipeline: [
    {
      id: "PRB-4092",
      clusterId: "CLUSTER-881",
      service: "Order-to-Cash Telematics Broker",
      recurringIncidents: 14,
      convertedToChange: true,
      changeId: "CR-8921",
      targetSprint: "Sprint 43 (Core Engineering Squad)",
      automatedSpecGenerated: true,
      roiImpact: "Prevents ~18 hrs P1 downtime / quarter"
    },
    {
      id: "PRB-4088",
      clusterId: "CLUSTER-882",
      service: "Dealer Invoicing Gateway",
      recurringIncidents: 8,
      convertedToChange: true,
      changeId: "CR-8914",
      targetSprint: "Sprint 42 (Commercial Product Backlog)",
      automatedSpecGenerated: true,
      roiImpact: "Reduces P2 ticket escalations by 80%"
    },
    {
      id: "PRB-4074",
      clusterId: "CLUSTER-883",
      service: "Fleet Edge Pipeline",
      recurringIncidents: 19,
      convertedToChange: false,
      changeId: "Pending Review",
      targetSprint: "Under Architectural Sizing",
      automatedSpecGenerated: true,
      roiImpact: "Saves ~45 hours triage / month"
    }
  ],
  applicationStability: [
    { name: "Telematics Core Ingestion", uptime: "99.98%", sla: "99.90%", status: "Optimal", incidents30d: 4 },
    { name: "Dealer Portal & Parts Exchange", uptime: "99.91%", sla: "99.85%", status: "Healthy", incidents30d: 11 },
    { name: "Global Billing & Invoicing", uptime: "99.95%", sla: "99.90%", status: "Optimal", incidents30d: 3 },
    { name: "Vehicle OTA Firmware Dispatch", uptime: "99.89%", sla: "99.85%", status: "Warning", incidents30d: 18 },
    { name: "Customer Identity & Auth SSO", uptime: "99.99%", sla: "99.95%", status: "Optimal", incidents30d: 1 }
  ],
  slaPerformance: {
    target: "99.0%",
    actual: "99.2%",
    errorBudgetRemaining: "84%",
    status: "Compliant",
    tiers: [
      { tier: "P1 (< 15m)", target: "99.5%", actual: "100%", breaches: 0, status: "Met" },
      { tier: "P2 (< 45m)", target: "98.0%", actual: "98.4%", breaches: 0, status: "Met" },
      { tier: "P3 (< 4h)", target: "95.0%", actual: "96.2%", breaches: 1, status: "Met" },
      { tier: "P4 (< 24h)", target: "95.0%", actual: "99.8%", breaches: 0, status: "Met" }
    ]
  },
  technicalDebtBacklog: {
    totalItems: 4,
    totalStoryPoints: 15,
    estCostOfInaction: "$85K / quarter in operational toil",
    items: [
      {
        id: "TD-201",
        title: "Legacy Telemetry Partition Threading Refactor",
        service: "Connected Vehicle Core",
        priority: "High",
        storyPoints: 5,
        recurringIncidents: 14,
        targetSquad: "Core Infrastructure Squad",
        status: "Synthesized by AI",
        crLinked: "CR-8921"
      },
      {
        id: "TD-202",
        title: "SAP OData Connection Pooler HikariCP Upgrade",
        service: "Dealer & Commercial API",
        priority: "Medium",
        storyPoints: 3,
        recurringIncidents: 8,
        targetSquad: "Commercial Platforms Squad",
        status: "Approved for Sprint 42",
        crLinked: "CR-8914"
      },
      {
        id: "TD-203",
        title: "Redis Cluster Distributed Lock & Multi-AZ Replicas",
        service: "Customer Identity & Auth SSO",
        priority: "Medium",
        storyPoints: 5,
        recurringIncidents: 6,
        targetSquad: "SecOps / Platform Eng",
        status: "Backlog Sizing",
        crLinked: "CR-8898"
      },
      {
        id: "TD-204",
        title: "UDP Socket Buffer Kernel Daemon Dynamic Auto-tune",
        service: "Fleet Edge Telemetry Pipeline",
        priority: "Low",
        storyPoints: 2,
        recurringIncidents: 19,
        targetSquad: "Edge Telemetry Ops",
        status: "Ready for Review",
        crLinked: "CR-8902"
      }
    ]
  },
  productivityAndCostReduction: {
    costSavedYtd: "$412,500",
    projectedAnnualSavings: "$850,000",
    engineeringHoursSaved: "1,240 hrs",
    fteCapacityReturned: "7.8 FTE software engineering velocity",
    ticketDeflectionRate: "62%",
    costPerTicket: "$9.20",
    baselineCostPerTicket: "$42.00",
    roiMultiplier: "4.6x"
  }
};

export const amsWorkflowInbox = [
  {
    id: "WF-INB-101",
    title: "Recurring P1 Cluster Remediation: Kafka Consumer Auto-Scale Runbook Approval",
    type: "Automation approvals",
    priority: "P1",
    riskLevel: "Critical",
    requestor: "AMS Self-Healing Orchestrator (Agent-KafkaOps-L4)",
    originatingSystem: "Datadog / PagerDuty / Kubernetes Operator",
    project: "Stellantis Connected Vehicle Telematics",
    portfolio: "Connected Customer Core",
    requiredDecision: "Approve Autonomous Production Pod Scaler & Partition Shuffler",
    dueDate: "Immediate (12 mins remaining)",
    status: "Pending Action",
    confidence: "94.8%",
    supportingEvidence: {
      metrics: "Consumer lag reached 142k messages on topic 'vehicle.telemetry.p1'. Queue depth growing at 12k/sec.",
      impact: "High latency on European vehicle emergency call (eCall) telemetry ingestion.",
      pastExecutions: "Executed successfully 5 times in staging with 0 regression.",
      rollbackPlan: "Automatic rollback to static replica count 6 if consumer error rate exceeds 0.02%."
    },
    aiRecommendation: "APPROVE. High confidence in partition distribution heuristics. Expected lag reduction to < 2,000 within 90 seconds.",
    decisionHistory: [
      { timestamp: "10:14 AM", actor: "Agent-KafkaOps", action: "Detected lag anomaly and generated remediation plan" },
      { timestamp: "10:15 AM", actor: "PolicyEngine", action: "Flagged action as High-Risk Production Tier-1 change; escalated to Tony (Head of AMS)" }
    ],
    auditTrail: "SHA256: 9bfa482ce... Verification status: Verified by Stellantis AI SecOps policy #SEC-882"
  },
  {
    id: "WF-INB-102",
    title: "Problem Record Review: PRB-4088 Unclosed Sessions in SAP Gateway",
    type: "Problem records requiring review",
    priority: "P2",
    riskLevel: "High",
    requestor: "AI Root Cause Synthesizer (Agent-RCA-Synthesizer)",
    originatingSystem: "ServiceNow Problem Management",
    project: "Dealer Invoicing & Part Catalog API",
    portfolio: "Commercial Operations",
    requiredDecision: "Validate Root Cause & Authorize Conversion to Engineering Change Request",
    dueDate: "Today, 5:00 PM CET",
    status: "Pending Review",
    confidence: "91.2%",
    supportingEvidence: {
      metrics: "8 recurring incidents over 48 hours. Cumulative downtime: 42 minutes.",
      impact: "Dealerships in France and Italy experiencing checkout retry timeouts during 11 AM peak.",
      pastExecutions: "AI analyzed heap dumps and pinpointed memory leak in SAPClientPool.java line 142.",
      rollbackPlan: "Not applicable (analytical problem record)."
    },
    aiRecommendation: "CONVERT TO SPRINT CHANGE. Automated pull request draft generated with fixed connection pool disposal.",
    decisionHistory: [
      { timestamp: "Yesterday 4:30 PM", actor: "ServiceNow Bot", action: "Grouped 8 incident tickets into PRB-4088" },
      { timestamp: "Yesterday 5:10 PM", actor: "Agent-RCA-Synthesizer", action: "Completed static code correlation with heap dump logs" }
    ],
    auditTrail: "SHA256: 4df876aa1... Cross-referenced with Git commit history on repo 'commercial/dealer-api'"
  },
  {
    id: "WF-INB-103",
    title: "Brownfield Pipeline Initiation: Legacy Order Management Modernization",
    type: "Brownfield pipeline initiation requests",
    priority: "P3",
    riskLevel: "Elevated",
    requestor: "Modernization Assistant (Agent-CodeLegacy-L2)",
    originatingSystem: "AMS Technical Debt Scanner",
    project: "Legacy Parts Dispatch AS/400 Gateway",
    portfolio: "Global Commercial Operations",
    requiredDecision: "Initiate Automated Containerization & API Facade Generation Pipeline",
    dueDate: "Tomorrow, 12:00 PM CET",
    status: "Pending Review",
    confidence: "88.5%",
    supportingEvidence: {
      metrics: "Cobol/C++ middleware responsible for 28% of monthly maintenance incidents.",
      impact: "Annual maintenance cost: $280,000 with slow patch deployment cycles.",
      pastExecutions: "Similar modernization successfully executed for Brazilian logistics gateway in Q2.",
      rollbackPlan: "Side-by-side canary proxy with 1% traffic shadow verification."
    },
    aiRecommendation: "APPROVE PIPELINE RUN. Initiate brownfield scan and test synthesis in isolated staging sandbox.",
    decisionHistory: [
      { timestamp: "Sep 11, 09:00 AM", actor: "TechDebtScanner", action: "Calculated technical debt index: 82/100" },
      { timestamp: "Sep 11, 02:15 PM", actor: "Agent-CodeLegacy", action: "Synthesized containerization blueprint" }
    ],
    auditTrail: "SHA256: 7aa9810bb... Reviewed against Enterprise Architecture Standards 2026"
  },
  {
    id: "WF-INB-104",
    title: "Incident Pattern Recommendation: GPS Ingestion Packet Drop Policy",
    type: "Incident pattern recommendations",
    priority: "P2",
    riskLevel: "High",
    requestor: "Telemetry Anomaly Detector",
    originatingSystem: "Dynatrace Davis AI",
    project: "Fleet Edge Telemetry Pipeline",
    portfolio: "Stellantis Cloud Platform",
    requiredDecision: "Apply Adaptive Rate Limiter & Edge Buffering Rule",
    dueDate: "Today, 6:00 PM CET",
    status: "Pending Action",
    confidence: "96.0%",
    supportingEvidence: {
      metrics: "19 packet drop spikes in 5 days due to telematics cellular bursts.",
      impact: "Temporary 2-minute telemetry blindspot for fleet tracking operators.",
      pastExecutions: "Simulated across 50,000 synthetic vehicles in digital twin environment.",
      rollbackPlan: "Single-click toggle in Envoy control plane."
    },
    aiRecommendation: "APPROVE DEPLOYMENT. Prevents UDP buffer drops while preserving zero data loss.",
    decisionHistory: [
      { timestamp: "Sep 12, 08:30 AM", actor: "Dynatrace Davis", action: "Detected pattern correlation across 12 edge nodes" }
    ],
    auditTrail: "SHA256: 12345feeb... Policy version: POL-TELEMETRY-v4.1"
  },
  {
    id: "WF-INB-105",
    title: "High-Risk Remediation: Production DB Deadlock Auto-Kill Script",
    type: "High-risk remediation actions",
    priority: "P1",
    riskLevel: "Critical",
    requestor: "Database Sentinel Agent (Agent-DBSentinel)",
    originatingSystem: "Postgres RDS Performance Insights",
    project: "Global Parts & Supply Chain DB",
    portfolio: "Enterprise ERP",
    requiredDecision: "Authorize Automated Termination of Blocking Transaction #tx-901842",
    dueDate: "Immediate (4 mins remaining)",
    status: "Pending Action",
    confidence: "98.1%",
    supportingEvidence: {
      metrics: "Lock wait time exceeded 180 seconds. 42 downstream order services queued.",
      impact: "Warehouse packing lines at Mirafiori plant temporarily halted.",
      pastExecutions: "Target query confirmed to be an unindexed ad-hoc analytics query from read-write master.",
      rollbackPlan: "Analytics session will receive standard timeout; read query can be retried on read-replica."
    },
    aiRecommendation: "APPROVE TERMINATION. Clear-cut ad-hoc blocking query starving tier-1 OLTP traffic.",
    decisionHistory: [
      { timestamp: "10:22 AM", actor: "Agent-DBSentinel", action: "Isolated blocking PID 41920" }
    ],
    auditTrail: "SHA256: 88ccff112... DB Governance Exception logged to Splunk SIEM"
  },
  {
    id: "WF-INB-106",
    title: "Production Governance Exception: Model Rate Limit Increase for Incident Triage",
    type: "Production governance exceptions",
    priority: "P3",
    riskLevel: "Low",
    requestor: "AMS Operations Center",
    originatingSystem: "AI Hub Gateway",
    project: "Autonomous Triage Cluster",
    portfolio: "IT Operations & Infrastructure",
    requiredDecision: "Raise Token Quota from 2M to 10M tokens/hr for OpsClaw-70B model",
    dueDate: "Sep 14, 05:00 PM CET",
    status: "Pending Review",
    confidence: "99.0%",
    supportingEvidence: {
      metrics: "Current token burn at 88% capacity during shift handover incident spikes.",
      impact: "Prevents triage throttling during multi-incident surges.",
      pastExecutions: "Budget headroom exists under AMS GenAI allocation pool.",
      rollbackPlan: "Quota can be dialed back instantly in Hub management console."
    },
    aiRecommendation: "APPROVE. Cost increase is under $180/month with zero operational risk.",
    decisionHistory: [
      { timestamp: "Sep 12, 09:15 AM", actor: "Tony / Head of AMS", action: "Requested review by Finance & Governance officer" }
    ],
    auditTrail: "SHA256: bb44ee110... Approved in principle by FinOps AI Committee"
  },
  {
    id: "WF-INB-107",
    title: "Feature Change Request: Self-Healing Telematics Partition Auto-Scaler (CR-8921)",
    type: "Feature change requests",
    priority: "P2",
    riskLevel: "Medium",
    requestor: "Autonomous Spec Generator (Agent-JiraSync-L3)",
    originatingSystem: "Jira Software / Engineering Backlog",
    project: "Connected Vehicle Telematics & Broker",
    portfolio: "Connected Customer Core",
    requiredDecision: "Authorize Injection of Feature CR-8921 into Sprint 43 Backlog (Core Engineering Squad)",
    dueDate: "Tomorrow, 3:00 PM CET",
    status: "Pending Review",
    confidence: "95.4%",
    supportingEvidence: {
      metrics: "Eliminates ~18 hrs P1 downtime / quarter by converting Kafka cluster rebalance mitigation into an active Kubernetes custom resource controller.",
      impact: "Zero customer disruption during European peak commute vehicle telemetry surges.",
      pastExecutions: "Verified in digital twin simulator with 100K synthetic vehicles.",
      rollbackPlan: "Feature flag 'feat.kafka.dynamic-scaler' disabled with instant fallback to standard HPA."
    },
    aiRecommendation: "APPROVE AND SYNC. High architectural alignment with Sprint 43 core infrastructure roadmap. Eliminates recurring CLUSTER-881 incident root cause permanently.",
    decisionHistory: [
      { timestamp: "11:20 AM", actor: "Agent-JiraSync", action: "Synthesized acceptance criteria & PR draft from PRB-4092" },
      { timestamp: "11:25 AM", actor: "Architecture Guard", action: "Passed automated security & scalability gate #SEC-914" }
    ],
    auditTrail: "SHA256: 34e89bb01... Linked Jira Epic: JIRA-STLA-4029 • Architectural Review Approved"
  }
];

export const amsExperienceData = {
  models: [
    {
      id: "MOD-001",
      name: "Claude 3.5 Sonnet",
      provider: "Anthropic",
      modality: "Multimodal (Text, Code, Vision)",
      deploymentType: "Dedicated Managed Endpoint",
      deployType: "Dedicated Sovereign Cloud",
      costTier: "Premium Compute",
      costTierPrice: "$0.015 / 1k tokens",
      capabilityGroup: "General Reasoning & Code",
      latency: "280ms P95",
      riskRating: "Medium",
      supportedUseCases: ["Executive Incident Post-Mortems", "Complex Cross-System Architecture Diagnostics", "Rapid Code Generation"],
      benchmarkScore: "96.8% Enterprise Reasoning",
      dataRestrictions: "Encrypted in transit and rest; Zero training retention",
      subscribed: true
    },
    {
      id: "MOD-002",
      name: "Claude 3 Opus",
      provider: "Anthropic",
      modality: "Text & Analytics",
      deploymentType: "Private Cloud (AWS Frankfurt)",
      deployType: "Multi-Tenant Cloud API",
      costTier: "Premium Compute",
      costTierPrice: "$0.030 / 1k tokens",
      capabilityGroup: "Deep & Complex Reasoning",
      latency: "420ms P95",
      riskRating: "Low",
      supportedUseCases: ["Deep Log Analysis", "Semantic Ticket Clustering", "Root Cause Analysis"],
      benchmarkScore: "98.7% Cluster Accuracy",
      dataRestrictions: "All enterprise telemetry permitted",
      subscribed: true
    },
    {
      id: "MOD-003",
      name: "Gemini 1.5 Pro",
      provider: "Google",
      modality: "Code & Architecture AST",
      deploymentType: "Hybrid Cloud",
      deployType: "Dedicated Sovereign Cloud",
      costTier: "Standard Compute",
      costTierPrice: "$0.012 / 1k tokens",
      capabilityGroup: "Multimodal Telemetry & Vision",
      latency: "320ms P95",
      riskRating: "High",
      supportedUseCases: ["Problem-to-Change Code Patching", "Brownfield AS/400 Modernization", "Unit Test Generation"],
      benchmarkScore: "89.4% HumanEval-Ops",
      dataRestrictions: "Requires Human-in-the-Loop review for PR merges",
      subscribed: false
    },
    {
      id: "MOD-004",
      name: "DeepSeek Coder V2",
      provider: "DeepSeek AI",
      modality: "Code & Scripts",
      deploymentType: "On-Prem Core Database Tier",
      deployType: "On-Premise Sovereign Cluster",
      costTier: "Economy Compute",
      costTierPrice: "$0.005 / 1k tokens",
      capabilityGroup: "General Reasoning & Code",
      latency: "150ms P95",
      riskRating: "Medium",
      supportedUseCases: ["Runbook Script Synthesis", "Automated DevOps Pipelines", "Code Optimization"],
      benchmarkScore: "95.1% Code Generation",
      dataRestrictions: "Confidential Tier-2 Enterprise Data permitted",
      subscribed: false
    },
    {
      id: "MOD-005",
      name: "GPT-4o",
      provider: "OpenAI",
      modality: "Text & Logs & Telemetry",
      deploymentType: "Dedicated On-Prem (Turin Datacenter)",
      deployType: "Dedicated Sovereign Cloud",
      costTier: "Premium Compute",
      costTierPrice: "$0.008 / 1k tokens",
      capabilityGroup: "Multimodal Telemetry & Vision",
      latency: "140ms P95",
      riskRating: "Medium",
      supportedUseCases: ["Log RCA Analysis", "SLA Breach Forecasting", "Incident Cluster Correlation"],
      benchmarkScore: "94.2% on OpsBench",
      dataRestrictions: "Confidential Tier-2 Enterprise Data permitted; No PII",
      subscribed: true
    },
    {
      id: "MOD-006",
      name: "Llama 3 70B",
      provider: "Meta AI",
      modality: "Multivariate Time-Series & Metrics",
      deploymentType: "Edge Gateway & AWS EU-West",
      deployType: "Private VPC Appliance",
      costTier: "Standard Compute",
      costTierPrice: "$0.003 / 1k data points",
      capabilityGroup: "Edge Simulation & Diagnostics",
      latency: "45ms P95",
      riskRating: "Low",
      supportedUseCases: ["Preventative Disk / RAM Spike Forecasting", "Vehicle Heartbeat Anomaly Isolation", "SLA Guard"],
      benchmarkScore: "97.4% Early Warning F1",
      dataRestrictions: "Vehicle Telemetry Tier-1 & Infrastructure Metrics approved",
      subscribed: false
    },
    {
      id: "MOD-007",
      name: "Mistral Large",
      provider: "Mistral AI",
      modality: "SQL AST & Execution Plans",
      deploymentType: "On-Prem Core Database Tier",
      deployType: "On-Premise Sovereign Cluster",
      costTier: "Standard Compute",
      costTierPrice: "$0.006 / 1k queries",
      capabilityGroup: "Deep & Complex Reasoning",
      latency: "65ms P95",
      riskRating: "Medium",
      supportedUseCases: ["Database Deadlock Auto-Mitigation", "Slow Query Plan Optimization", "Index Recommendations"],
      benchmarkScore: "95.1% Plan Optimization",
      dataRestrictions: "Internal DBA credentials required; Zero external exposure",
      subscribed: false
    },
    {
      id: "MOD-008",
      name: "Claude 3 Haiku",
      provider: "Anthropic",
      modality: "Text & Fast Analytics",
      deploymentType: "Managed Cloud Endpoint",
      deployType: "Multi-Tenant Cloud API",
      costTier: "Economy Compute",
      costTierPrice: "$0.002 / 1k tokens",
      capabilityGroup: "General Reasoning & Code",
      latency: "95ms P95",
      riskRating: "Low",
      supportedUseCases: ["Fast Log Triage", "Customer Support Auto-Responder", "Live Chat Assistant"],
      benchmarkScore: "92.4% Fast Response",
      dataRestrictions: "Enterprise agreement restrictions apply",
      subscribed: false
    },
    {
      id: "MOD-009",
      name: "Gemini 1.5 Flash",
      provider: "Google",
      modality: "Fast Multimodal",
      deploymentType: "Cloud API",
      deployType: "Multi-Tenant Cloud API",
      costTier: "Economy Compute",
      costTierPrice: "$0.003 / 1k tokens",
      capabilityGroup: "Multimodal Telemetry & Vision",
      latency: "120ms P95",
      riskRating: "Low",
      supportedUseCases: ["High-Volume Camera Log Tagging", "Sensory Data Pre-Processing", "Quick Document Summarization"],
      benchmarkScore: "90.1% Visual Accuracy",
      dataRestrictions: "EU processing only",
      subscribed: false
    },
    {
      id: "MOD-010",
      name: "Llama 3 8B",
      provider: "Meta AI",
      modality: "Text & Code",
      deploymentType: "Local Edge Device",
      deployType: "Private VPC Appliance",
      costTier: "Economy Compute",
      costTierPrice: "$0.000 / 1k tokens (Local)",
      capabilityGroup: "Edge Simulation & Diagnostics",
      latency: "25ms P95",
      riskRating: "Low",
      supportedUseCases: ["In-Vehicle Diagnostics", "Offline Code Review", "Low-Latency Edge Inference"],
      benchmarkScore: "88.2% Edge Benchmark",
      dataRestrictions: "Fully isolated, zero egress",
      subscribed: false
    },
    {
      id: "MOD-011",
      name: "Cohere Command R+",
      provider: "Cohere",
      modality: "RAG & Enterprise Search",
      deploymentType: "Private Cloud Server",
      deployType: "Dedicated Sovereign Cloud",
      costTier: "Standard Compute",
      costTierPrice: "$0.010 / 1k tokens",
      capabilityGroup: "General Reasoning & Code",
      latency: "210ms P95",
      riskRating: "Medium",
      supportedUseCases: ["RAG over Internal Docs", "Enterprise Knowledge Search", "Complex Query Resolution"],
      benchmarkScore: "96.5% Retrieval Accuracy",
      dataRestrictions: "Approved for internal knowledge bases",
      subscribed: false
    },
    {
      id: "MOD-012",
      name: "AI21 Jamba",
      provider: "AI21 Labs",
      modality: "Text & Reasoning",
      deploymentType: "Managed Cloud",
      deployType: "Multi-Tenant Cloud API",
      costTier: "Standard Compute",
      costTierPrice: "$0.009 / 1k tokens",
      capabilityGroup: "Deep & Complex Reasoning",
      latency: "250ms P95",
      riskRating: "Low",
      supportedUseCases: ["Long-Context Document Analysis", "Legal Document Review", "Technical Manual Parsing"],
      benchmarkScore: "93.8% Context Retention",
      dataRestrictions: "Standard NDAs apply",
      subscribed: false
    }
  ],
  agents: [
    {
      id: "AGT-01",
      name: "Kafka Cluster Self-Healing Agent",
      owner: "Tony / Head of AMS",
      autonomyLevel: "L4 Autonomous with Guardrails",
      lifecycleStage: "Production Active",
      status: "Active",
      riskRating: "High",
      domain: "Operations & Messaging Infrastructure",
      technology: "Go / Kubernetes Operator / Kafka Admin API",
      purpose: "Detects partition rebalance storms, consumer lag buildup, and automatically shifts topic partitions or scales consumer pods.",
      inputs: "Kafka consumer lag metrics, partition offsets, telemetry pod memory usage",
      outputs: "Dynamic partition reassignment plan, HPA replica scale commands",
      modelDependencies: "OpsClaw-70B-Remediation",
      project: "Connected Vehicle Telematics & Broker",
      metrics: "74 auto-heal actions this month, 0 false positives, 100% SLA preserved",
      permissions: ["k8s.apps.scale", "kafka.rebalance.execute", "pagerduty.incident.resolve"]
    },
    {
      id: "AGT-02",
      name: "RCA & Post-Mortem Synthesizer",
      owner: "Tony / Head of AMS",
      autonomyLevel: "L3 Collaborative",
      lifecycleStage: "Production Active",
      status: "Active",
      riskRating: "Low",
      domain: "Application Incident Management",
      technology: "Python / LangGraph / Datadog API / ServiceNow",
      purpose: "Extracts stack traces, metric anomalies, and code diffs across P1/P2 incidents to generate 5-Why analysis and executive post-mortem.",
      inputs: "ServiceNow incident tickets, Dynatrace crash traces, git commit diffs",
      outputs: "Root cause synthesis document, Confluence executive post-mortem page",
      modelDependencies: "Claude-3.5-Sonnet-Enterprise",
      project: "Enterprise Core Application Management",
      metrics: "Average post-mortem turnaround reduced from 3 days to 14 minutes",
      permissions: ["datadog.logs.read", "github.commits.read", "servicenow.problem.write"]
    },
    {
      id: "AGT-03",
      name: "Problem-to-Change Generator",
      owner: "Tony & Alex Joint Governance",
      autonomyLevel: "L3 Supervised",
      lifecycleStage: "Production Active",
      status: "Active",
      riskRating: "Medium",
      domain: "Engineering Operations & Backlog Bridge",
      technology: "Node.js / Jira REST API / GitLab CI",
      purpose: "Groups recurring incident patterns and automatically formats production-ready Jira User Stories and Architecture Change Requests.",
      inputs: "ServiceNow recurring problem tickets, telemetry clustering logs",
      outputs: "Jira User Stories, acceptance criteria, draft GitLab merge requests",
      modelDependencies: "OpsClaw-70B-Remediation",
      project: "Connected Customer Core Platform",
      metrics: "24 Change Requests synthesized; 18 accepted into sprint planning",
      permissions: ["jira.issue.create", "gitlab.mr.create", "confluence.doc.write"]
    },
    {
      id: "AGT-04",
      name: "DB Query Deadlock Sentinel",
      owner: "Tony / Head of AMS",
      autonomyLevel: "L2 Assisted",
      lifecycleStage: "Experimental",
      status: "Experimental",
      riskRating: "High",
      domain: "Database Reliability",
      technology: "Python / Postgres Admin / Splunk SIEM",
      purpose: "Monitors transaction locks and suggests or executes query cancellations for non-critical ad-hoc analytical locks.",
      inputs: "Postgres pg_stat_activity logs, lock wait duration metrics",
      outputs: "PID termination recommendation, SIEM security audit event",
      modelDependencies: "SQL-Autonomous-Query-Optimizer",
      project: "Global Parts & Supply Chain DB",
      metrics: "Tested on 12 deadlocks in staging; prevented 3 cascading DB halts",
      permissions: ["rds.pg_terminate_backend.execute"]
    },
    {
      id: "AGT-05",
      name: "Legacy AS/400 Direct DB Mutator",
      owner: "Enterprise Modernization Board",
      autonomyLevel: "L1 Assisted",
      lifecycleStage: "Suspended",
      status: "Suspended",
      riskRating: "High",
      domain: "Legacy Integration",
      technology: "RPG / AS/400 Connect / Java Gateway",
      purpose: "Automates direct transactional record synchronization with legacy parts warehouse hosts.",
      inputs: "Order reconciliation batch files",
      outputs: "Direct DB2 ledger updates",
      modelDependencies: "CodeLlama-AMS-Refactor",
      project: "Legacy Commercial AS/400 Modernization",
      metrics: "Suspended pending SOC2 Phase-3 compliance audit verification",
      permissions: ["as400.db2.write.restricted"]
    },
    {
      id: "AGT-06",
      name: "Regex Log Matcher & Grep Daemon",
      owner: "Legacy Monitoring Squad",
      autonomyLevel: "L1 Rule-Based",
      lifecycleStage: "Retired",
      status: "Retired",
      riskRating: "Low",
      domain: "Legacy Telemetry",
      technology: "Perl / Bash / Rsyslog",
      purpose: "Static rule-based error log scanning prior to GenAI semantic clustering adoption.",
      inputs: "Plain text log files from syslog",
      outputs: "Email alerts to on-call engineers",
      modelDependencies: "None (Deprecated)",
      project: "Legacy EMEA Monitoring",
      metrics: "Retired in Q1 2026 in favor of Incident-Triage-Embeddings-v2",
      permissions: ["syslog.read"]
    }
  ],
  tools: [
    {
      id: "TOOL-01",
      name: "Dynatrace Davis AI Root Cause Engine",
      category: "Observability tools",
      description: "Autonomous full-stack APM anomaly detection with causal topological AI analysis.",
      useCases: "Service degradation detection, microservice latency tracing, distributed transaction mapping",
      integrationRequirements: "OneAgent daemon on all Kubernetes nodes, OpenTelemetry exporter",
      licensing: "Enterprise License Agreement (ELA)",
      approvedProjects: ["All Tier-1 & Tier-2 Applications"],
      securityClassification: "Classified Internal",
      dataHandlingRestrictions: "Strict masking of vehicle VINs and driver PII",
      supportOwner: "AMS Infrastructure Team",
      subscriptionProcess: "Automatic provisioning via Terraform enterprise workspace",
      adoptionRate: "94% across 84 enterprise microservices",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-02",
      name: "GitHub Copilot Enterprise for AMS Fixes",
      category: "Coding assistants",
      description: "AI pair programmer fine-tuned for rapid incident remediation and bug fixes.",
      useCases: "Generating runbook scripts, fixing null pointer leaks, writing regression tests",
      integrationRequirements: "GitHub Enterprise Cloud SSO, VS Code / JetBrains IDE extension",
      licensing: "User-based seat allocation (250 seats active)",
      approvedProjects: ["All AMS Engineering Squads", "ServiceNow Core", "CI/CD Gateways"],
      securityClassification: "Restricted - No customer personal data in prompts",
      dataHandlingRestrictions: "Zero retention policy; enterprise privacy filter active",
      supportOwner: "Alex / Chief AI Officer Team",
      subscriptionProcess: "Manager approval via Stellantis ServiceDesk Portal",
      adoptionRate: "78% engineer adoption in AMS dev squad",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-03",
      name: "Playwright AI Autonomous Test Synthesizer",
      category: "Testing tools",
      description: "Autonomous end-to-end regression test generator driven by production incident replays.",
      useCases: "Post-incident regression verification, UI journey testing, API boundary fuzzing",
      integrationRequirements: "GitLab CI/CD runners, Headless Chromium Docker agents",
      licensing: "Open-Source Apache 2.0 with Enterprise Support Addon",
      approvedProjects: ["Dealer Portal", "Fleet Management Web", "Customer SSO"],
      securityClassification: "Internal Core",
      dataHandlingRestrictions: "Synthetic test fixtures only; production data scrubbing enforced",
      supportOwner: "Quality Engineering COE",
      subscriptionProcess: "Self-service project enablement via CI pipeline templates",
      adoptionRate: "82% test coverage on critical commercial portals",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-04",
      name: "Ardoq Enterprise AI Architecture Graph",
      category: "Architecture tools",
      description: "Dynamic enterprise architecture mapping correlating services, APIs, and business capabilities.",
      useCases: "Blast radius modeling, API dependency audits, technical debt topology tracking",
      integrationRequirements: "ServiceNow CMDB sync, AWS CloudFormation / Terraform metadata connector",
      licensing: "Enterprise Architecture Tier",
      approvedProjects: ["All Global Software Programs"],
      securityClassification: "Internal Strategic",
      dataHandlingRestrictions: "Internal architecture metadata only; no runtime telemetry",
      supportOwner: "Enterprise Architecture Board",
      subscriptionProcess: "Role-based entitlement for Tech Leads and Architects",
      adoptionRate: "100% core services mapped in real-time graph",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-05",
      name: "Harness AI Chaos & Deployment Canary",
      category: "DevOps tools",
      description: "AI-driven automated canary analysis and chaos engineering experiment runner.",
      useCases: "Autonomous rollback verification, traffic shifting, failure injection testing",
      integrationRequirements: "Kubernetes ArgoCD connector, Prometheus metric telemetry feed",
      licensing: "Enterprise DevOps Platform License",
      approvedProjects: ["Connected Vehicle Core", "Order Management APIs"],
      securityClassification: "Classified Internal",
      dataHandlingRestrictions: "Encrypted metrics only; zero application payload inspection",
      supportOwner: "Cloud Platform SRE Squad",
      subscriptionProcess: "SRE Lead sign-off required per cluster namespace",
      adoptionRate: "89% automated canary pass rate in staging",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-06",
      name: "dbt Cloud AI Pipeline Optimizer",
      category: "Data engineering tools",
      description: "Automated SQL telemetry pipeline synthesis, model optimization, and data lineage tracking.",
      useCases: "Snowflake query acceleration, data warehouse cost reduction, telemetry pipeline lineage",
      integrationRequirements: "Snowflake Enterprise Data Cloud, Git repository sync",
      licensing: "Team Consumption Tier",
      approvedProjects: ["Fleet Analytics Warehouse", "Global Telemetry Data Lake"],
      securityClassification: "Classified Internal",
      dataHandlingRestrictions: "Pseudonymized telemetry tokens; strict GDPR compliance",
      supportOwner: "Data Platform Engineering",
      subscriptionProcess: "Service account token provisioning via Vault",
      adoptionRate: "72% data engineering team adoption",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-07",
      name: "Cast Software Brownfield Architecture Analyzer",
      category: "Modernization tools",
      description: "Software intelligence engine providing deep architectural insights into legacy codebases.",
      useCases: "AS/400 and COBOL refactoring, monolithic code decoupling, security flaw identification",
      integrationRequirements: "Source code repository read access, Jenkins/GitLab scanner daemon",
      licensing: "Portfolio Project License",
      approvedProjects: ["Legacy AS/400 and SAP Modernization Programs"],
      securityClassification: "Internal Core",
      dataHandlingRestrictions: "Source code analysis in private VPC boundary only",
      supportOwner: "Enterprise Architecture Board",
      subscriptionProcess: "Modernization squad project allocation",
      adoptionRate: "6 legacy core portfolios assessed",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-08",
      name: "Glean Enterprise Knowledge & Runbook Search",
      category: "Documentation and knowledge tools",
      description: "GenAI search across Confluence, Jira, ServiceNow, Slack, and code repositories.",
      useCases: "Instant SOP and runbook discovery during active P1 triage, post-mortem research",
      integrationRequirements: "Okta SSO, Google Workspace, Jira/ServiceNow enterprise connectors",
      licensing: "Enterprise Site License (All Stellantis IT & Engineering)",
      approvedProjects: ["Company-Wide Access"],
      securityClassification: "Internal General",
      dataHandlingRestrictions: "Strict ACL inheritance; users only see documents they have rights to",
      supportOwner: "IT Knowledge Operations",
      subscriptionProcess: "Auto-provisioned on corporate SSO login",
      adoptionRate: "91% daily active usage across support engineers",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-09",
      name: "SonarQube AI Code Security Engine",
      category: "Security and compliance tools",
      description: "Continuous code quality, secret detection, and AI vulnerability remediation suggestions.",
      useCases: "Automated PR security gates, CVE dependency vulnerability scanning, SAST checks",
      integrationRequirements: "GitLab CI/CD integration, SonarLint IDE plugins",
      licensing: "Enterprise Server Tier",
      approvedProjects: ["All CI/CD Pipeline Gates"],
      securityClassification: "Internal Core",
      dataHandlingRestrictions: "Static code inspection; no sensitive credentials logged",
      supportOwner: "Cybersecurity & DevSecOps",
      subscriptionProcess: "Mandatory default gate on all active git repositories",
      adoptionRate: "100% mandatory gate on all repo PRs",
      status: "Approved & Operational"
    },
    {
      id: "TOOL-10",
      name: "Productboard AI Epic & Story Synthesizer",
      category: "Product-management tools",
      description: "Translates operational AMS problem tickets directly into prioritized product features.",
      useCases: "Customer feedback clustering, backlog prioritization, roadmap alignment with Engineering and Product squads",
      integrationRequirements: "Jira Software bi-directional sync, Salesforce customer feedback API",
      licensing: "Product Management Enterprise Seats",
      approvedProjects: ["Connected Customer Portal", "Dealer Operating Platform"],
      securityClassification: "Internal Commercial",
      dataHandlingRestrictions: "Commercial feature roadmaps; no telemetry payloads",
      supportOwner: "Product Operations Lead",
      subscriptionProcess: "Product Owner seat license request",
      adoptionRate: "85% product owner alignment",
      status: "Approved & Operational"
    }
  ],
  mySubscriptions: [
    {
      id: "SUB-01",
      entityName: "Claude 3.5 Sonnet",
      type: "Model",
      level: "Portfolio level",
      status: "Active",
      renewalDate: "2026-12-31",
      monthlyUsage: "48.2M tokens (72% of 65M cap)",
      costAllocation: "$385 / month",
      grantedBy: "Chief AI Officer / Enterprise Governance"
    },
    {
      id: "SUB-01B",
      entityName: "Claude 3 Opus",
      type: "Model",
      level: "Portfolio level",
      status: "Active",
      renewalDate: "2026-12-31",
      monthlyUsage: "12.4M tokens (30% of 40M cap)",
      costAllocation: "$210 / month",
      grantedBy: "Head of AMS (Tony)"
    },
    {
      id: "SUB-01C",
      entityName: "GPT-4o",
      type: "Model",
      level: "Portfolio level",
      status: "Active",
      renewalDate: "2026-12-31",
      monthlyUsage: "8.1M tokens (15% of 50M cap)",
      costAllocation: "$150 / month",
      grantedBy: "Head of AMS (Tony)"
    },
    {
      id: "SUB-02",
      entityName: "Kafka Cluster Self-Healing Agent",
      type: "Agentic workflow",
      level: "Team level",
      status: "Active",
      renewalDate: "Continuous",
      monthlyUsage: "74 autonomous interventions",
      costAllocation: "$0 (Internal Infra)",
      grantedBy: "Head of AMS (Tony)"
    },
    {
      id: "SUB-03",
      entityName: "RCA & Post-Mortem Synthesizer",
      type: "Agent",
      level: "Enterprise level",
      status: "Active",
      renewalDate: "Continuous",
      monthlyUsage: "112 post-mortems generated",
      costAllocation: "$120 / month",
      grantedBy: "Alex / CAIO Board"
    },
    {
      id: "SUB-04",
      entityName: "Dynatrace Davis AI Root Cause Engine",
      type: "AI tool",
      level: "Enterprise level",
      status: "Active",
      renewalDate: "2027-03-31",
      monthlyUsage: "1,400 monitored agent hosts",
      costAllocation: "Corporate ELA",
      grantedBy: "IT Operations & Infrastructure"
    },
    {
      id: "SUB-05",
      entityName: "Connected Vehicle Telematics Modernization",
      type: "Project",
      level: "Project level",
      status: "Active",
      renewalDate: "Sprint 44 Handover",
      monthlyUsage: "18 active change requests tracked",
      costAllocation: "$0 (CapEx Project)",
      grantedBy: "Portfolio Delivery Lead"
    },
    {
      id: "SUB-06",
      entityName: "Real-Time P1 Outage Escalation SMS & Pager",
      type: "Notification",
      level: "Individual level",
      status: "Active",
      renewalDate: "Self-Managed",
      monthlyUsage: "4 emergency pages this week",
      costAllocation: "$0 (Telecom Pool)",
      grantedBy: "Tony / User Profile"
    },
    {
      id: "SUB-07",
      entityName: "Production Safe Remediation Governance Policy #GOV-901",
      type: "Governance policy",
      level: "Portfolio level",
      status: "Active & Enforced",
      renewalDate: "Annual Audit Oct 2026",
      monthlyUsage: "Enforced across 14 automation runbooks",
      costAllocation: "$0 (Compliance Mandate)",
      grantedBy: "Enterprise Architecture & SecOps"
    },
    {
      id: "SUB-08",
      entityName: "Executive Incident Velocity & MTTD Scorecard",
      type: "Report / dashboard",
      level: "Portfolio level",
      status: "Active",
      renewalDate: "Continuous Sync",
      monthlyUsage: "Daily 07:00 automated executive dispatch",
      costAllocation: "$0",
      grantedBy: "AMS Analytics Hub"
    }
  ]
};
